- explainer.md
Updated this file to include clearer language.
> Clarified language

- explainer.md
Added Deliverable Status as Approved Draft to explainer.md
> Added Deliverable Status

- spec/spec.md
First take of using DagJOSE as the secure object envelope.
> feat: dag-jose

- spec/spec.md
The interface APIs are still pseudo-reflections of the objects that would be sent, but this attempts to update it to get it looking more the shape/set desired (imo). Acceptance of this PR does not indicate this is how the final interfaces and their invoking objects will look.
> Update pseudo formats for interface APIs

- spec/spec.md
This is specifically adding the DID-relative variant of Hub URLs, but more variants can be added as we build this section of the spec out.
> Add initial content for Hub URL addressing

- spec/spec.md
> Improve language in spec.md

- spec/index.html
- spec/spec.md
so interop is not hindered while people search for a secp265k1 curve 
😂
> spec typo ES265K -> ES256K

- package-lock.json
- spec/index.html
- spec/spec.md
Took a swing at getting the basics for the Permissions interface into a PR. Work on Permissions is not complete, as various processing steps must be defined for things like invocation evaluation and revocation closure of permitted invocations/objects.
> First pass at Permissions

- spec/spec.md
This text seems unintentionally placed in this doc.
> Remove irrelevant note about seattle vet specialists

- docs/companion_guide.md
Questions from the AMA call.
Quick note on this: This is still a DRAFT. I took these notes on the fly, and need to prepare the responses better and clean up a lot of the wording.
> companion guide: ama questions

- docs/agenda.md
> Notes for Agenda March 22, 2023

- spec/spec.md
> fix codefenced language from `json5` to `json`

- docs/companion_guide.md
Related to https://github.com/decentralized-identity/decentralized-web-node/issues/152
> Local, Remote, and Relay Nodes.

- docs/companion_guide.md
This is intended to be a DRAFT. To discuss over next DIF DWN call. It's a starting point, but this will need to be reviewed, and then cleaned up, post alignment. 
After going through this exercise myself, I found it somewhat difficult sometimes to bucket into the categories that were defined. Not sure what the solution is here, but maybe we can change some of the categories a little. 
There's a few sections I think would be helpful to add in, and also need to revisit a few of the bullets. 
A few suggestions to consider and discuss over the next call:
1. Add sync as part of the evaluation criteria . 
2. Add supportable backends as part of the matrix.
> added dwn and peergos to the comparison guide

- docs/agenda.md
Meeting notes from DIF 2023-05-31
> May 31 Meeting Notes

- docs/agenda.md
> agenda notes 07-21-2023

- spec/spec.md
Initial pass at attempting to align `Protocols` in the spec with what's implemented.
> Update Protocols Spec Definitions

- schemas/json-schemas/authorization-payloads/base-authorization-payload.json
- schemas/json-schemas/authorization-payloads/records-write-authorization-payload.json
- schemas/json-schemas/hooks/hooks-write.json
- schemas/json-schemas/interface-methods/messages-get.json
- schemas/json-schemas/interface-methods/permissions-definitions.json
- schemas/json-schemas/interface-methods/permissions-grant.json
- schemas/json-schemas/interface-methods/permissions-request.json
- schemas/json-schemas/interface-methods/permissions-revoke.json
- schemas/json-schemas/interface-methods/protocol-definition.json
- schemas/json-schemas/interface-methods/protocol-rule-set.json
- schemas/json-schemas/interface-methods/protocols-configure.json
- schemas/json-schemas/interface-methods/protocols-query.json
- schemas/json-schemas/interface-methods/records-delete.json
- schemas/json-schemas/interface-methods/records-query.json
- schemas/json-schemas/interface-methods/records-read.json
- schemas/json-schemas/interface-methods/records-write.json
- schemas/json-schemas/interface-methods/snapshots-create.json
updated schemas from dwn-sdk-js with more recent versions.
> updated schemas with latest

- LICENSE
added license file. Tagging @paulgrehan  for review.
> added Apache 2.0 License to repo

- spec/spec.md
> updated recordsDelete

- spec/spec.md
dependent on #250 . I will rebase after merge. Adds records query documentation in [c8512dc](https://github.com/decentralized-identity/decentralized-web-node/pull/256/commits/c8512dc67334e416ca68c5d3f2842995908833cd)
> update records query

- docs/agenda.md
> Updated agenda.md

- docs/companion_guide.md
adding license to companion guide
> adding license to companion guide

- README.md
- docs/companion_guide.md
- package-lock.json
- spec/spec.md
- specs.json
updated README and specs.json file. Now resolvable url should be available for companion guide.
> updated README and spec.json

- specs.json
> Update the public root.

- specs.json
> move spec outputs to root path.

- docs/companion_guide.md
Changes in this PR updates information about Personal Data Stores section about Solid to more accurately reflect definitions and current development.
> Update Personal Data Stores section about Solid.

- spec/spec.md
First pass at protocol examples/explainer. Could be built on with more info/better language but is a good starting point.
Part of https://github.com/decentralized-identity/decentralized-web-node/issues/289
> protocol introduction section
